# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

name: Trips-Go-Build

parameters:
- name: succeed
  displayName: Check true to fail
  type: boolean
  default: false

trigger:
  branches: 
    include:
    - none 
  paths:
    include:
    - apis/trips/*
    exclude:
      - apis/poi/*
      - apis/user-java/*
      - apis/userprofile/*

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  steps: 
  - task: GoTool@0
    inputs:
      version: '1.13.5'
  - task: Go@0
    displayName: Go Get
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips/*'
  - task: Go@0
    displayName: Go Build
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips/main.go'
  - task: Go@0
    displayName: Go Test
    inputs:
      command: 'test'
      workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips/tests/'

  - task: CopyFiles@2
    displayName: Copy files
    inputs:
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: drop

# This job creates a work item, and only runs if the previous job failed
- job: ErrorHandler
  dependsOn: Build
  condition: failed()
  steps: 
  - bash: |
      az boards work-item create --title "Build $(build.buildNumber) failed" \
        --type bug --org $(System.TeamFoundationCollectionUri) \
        --project $(System.TeamProject)
    env: 
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
    displayName: 'Create work item on failure'