# Default values for helmv2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
productionSlot: blue
blue:
  enabled: true
  tag: latest

green:
  enabled: false
  tag: latest

replicaCount: 2
repository:
  # Fully qualified path to image in ACR (Ex. youracr.azurecr.io/devopsoh/poi-build).
  # See deployment scripts in https://github.com/Azure-Samples/openhack-devops-proctor for example usage.
  image:
  pullPolicy: Always
image:
  name: user-java
  label: user-java
  containerPort: 8080
service:
  externalPort: 80
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  rules:
    endpoint:
      #fqdn of your exposed application (found in ohteamvalues file)
      host:
      paths:
      - path: /api/user-java
        serviceName: api-user-java-svc
        servicePort: 80
      - path: /api/healthcheck/user-java
        serviceName: api-user-java-svc
        servicePort: 80
      - path: /api/documentation/user-java
        serviceName: api-user-java-svc
        servicePort: 80
      - path: /api/docs/user-java
        serviceName: api-user-java-svc
        servicePort: 80
      - path: /api/swagger-resources
        serviceName: api-user-java-svc
        servicePort: 80
      - path: /api/api-docs
        serviceName: api-user-java-svc
        servicePort: 80

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
