trigger:
  branches:
    include:
    - master
  paths:
    include:
    - apis/poi/*
  
pr:
  branches:
    include:
    - master
  paths:
    include:
    - apis/poi/*
  
pool:
  vmImage: 'Ubuntu-18.04'

steps:  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '/apis/poi/web/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '/apis/poi/tests/UnitTests/*.csproj'