pipeline {
  agent {
    label "docker"
  }
  stages {
    stage('build') {
      steps {
        script {
          registry =  "openhackiva6acr.azurecr.io"
        }
        withCredentials([usernamePassword(credentialsId: '6f81a13c-2f1b-4547-b66b-5968150d8add', passwordVariable: 'PASSWORD_REGISTRY', usernameVariable: 'USERNAME_REGISTRY')]) {
          sh "docker login ${registry} --username ${USERNAME_REGISTRY} --password ${PASSWORD_REGISTRY}"
        }
        script { 
          image = "${registry}/poi:${env.BRANCH_NAME}-${BUILD_NUMBER}"
        }
        sh "docker build -t ${image} apis/poi/web"
        sh "docker push ${image}"
      }
    }
  }
}
