pipeline {
    agent any

     environment {
         APP_IMAGE_REPOSITORY_NAME = 'devopsoh/api-poi'
         SRC_DIR = 'apis/poi'
    }

    stages {
        stage('Build') {
            steps {
               dir("${env.SRC_DIR}") {
                   sh 'dotnet build --configuration Release'
               }
            }
        }

        stage('Test') {
            steps {
                echo 'Testing... a sep file'
            }
        }

        stage('Build Docker Image') {
           steps {
               dir("${env.SRC_DIR}/web") {
                   sh "docker build -t ${ACR_LOGINSERVER}/${env.APP_IMAGE_REPOSITORY_NAME}:${env.BUILD_NUMBER} ."
               }
           }
       }

       stage('Push Docker Image to Registry') {
           steps {
               dir("${env.SRC_DIR}/web") {
                   withDockerRegistry(credentialsId: 'acrcreds', url: "https://${ACR_LOGINSERVER}") {
                       sh "docker push ${ACR_LOGINSERVER}/${env.APP_IMAGE_REPOSITORY_NAME}:${env.BUILD_NUMBER}"
                   }
               }
           }
       }
    }
}
