apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.image.name }}-deploy"
  labels:
    deploy: {{ .Values.image.label }}
spec:
  progressDeadlineSeconds: 60
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailablePercentage}}
      maxSurge: {{ .Values.rollingUpdate.maxSurgePercentage}}
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.image.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.label }}
    spec:
      containers:
      - image: "{{ .Values.repository.image }}:{{ .Values.repository.tag }}"
        imagePullPolicy: {{ .Values.repository.pullPolicy }}
        name: {{ .Values.image.name }}
        ports:
          - containerPort: {{ .Values.image.containerPort }}
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/healthcheck/user-java
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql
                key: sql_user
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql
                key: sql_password
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sql
                key: sql_server
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sql
                key: sql_dbname
