apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.label }}-{{ .Values.image.slot }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.image.label }}
    slot: {{ .Values.image.slot }}
  ports:
    - protocol: TCP
      name: {{ .Values.image.name }}-http
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.image.containerPort }}
    - protocol: TCP
      name: {{ .Values.image.name }}-https
      port: 443
      targetPort: 443
