pipeline{
      agent  { node { label 'master' } }

stages
{
    stage('checkout')
    {
        steps
        {
            git branch: 'feature-d', credentialsId: 'c018860d-89a7-4e2e-ada5-d79677da19f1', url: 'https://github.com/hattan/openhack-devops-team'
        }
    }
    stage('setup')
    {
        steps
        {
            withCredentials([[$class: 'UsernamePasswordMultiBinding',
            credentialsId: 'acr-creds',
            usernameVariable: 'ACR_USER',
            passwordVariable: 'ACR_PASSWORD']])
            {
                sh  "docker -H tcp://${DOCKER_BUILD_PUSH_HOST} login ${ACR_ENDPOINT} -u '${ACR_USER}' -p '${ACR_PASSWORD}'"
            }       
        }
    }
    stage('build')
    {
        steps
        {
           sh "docker -H tcp://${DOCKER_BUILD_PUSH_HOST} build -t ${ACR_ENDPOINT}/team4-poi:${BUILD_TAG} -f $WORKSPACE/apis/poi ."
        }
    }
        stage('push')
    {
        steps
        {
            sh  "docker -H tcp://${DOCKER_BUILD_PUSH_HOST} push ${ACR_ENDPOINT}/team4-poi:${BUILD_TAG}"
            
        }
    }
    stage('helm install')
    {
        steps
        {
           sh "helm version --client"
        }
    }
}
    post { 
        always { 
            echo 'Post Build Results'
                                  script {
    properties([[$class: 'GithubProjectProperty',
                projectUrlStr: 'https://github.com/hattan/openhack-devops-team']])
}
step([$class: 'GitHubIssueNotifier',
      issueAppend: true,
      issueLabel: '',
      issueTitle: '$JOB_NAME $BUILD_DISPLAY_NAME failed'])
        }
    }
}
