apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-istio
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - istio.local
    - istiodevopsoh.eastus.cloudapp.azure.com
    port:
      name: http
      number: 80
      protocol: HTTP
