pipeline {
    agent any

    tools {
        maven '3.5.4'
    }

    environment {
        APP_NAME = 'devopsoh/api-user-java'
        SRC_DIR = 'apis/user-java'
    }

    stages{
        stage('Code Test') {
            steps {
                sh '''
                    mvn test
                '''
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${env.SRC_DIR}") {
                    script {
                        docker.build("${env.APP_NAME}:${env.BUILD_ID}")
                    }
                }
            }
        }

        stage('Upload Docker Image to ACR') {
            steps {
                script {
                    withDockerRegistry(credentialsId: '162a5f2f-bc39-4c82-a67b-7b9eedb3afe4', url: 'https://openhacktce4acr.azurecr.io') {
                        docker.push("${env.APP_NAME}:${env.BUILD_ID}")
                    }
                }
            }
        }
    }
}