pipeline{
  agent  { node { label 'master' } }

  environment {
    BUID_TAG = "ujpr${env.BUILD_NUMBER}"
  }

  stages {
    stage('login') {
      steps
      {
        withCredentials([[$class: 'UsernamePasswordMultiBinding',
        credentialsId: 'AzureACRCreds',
        usernameVariable: 'ACR_USER',
        passwordVariable: 'ACR_PASSWORD']])
        {
          sh  "docker login ${env.ACR_ENDPOINT} -u '${ACR_USER}' -p '${ACR_PASSWORD}'"
        }   
      }
    }
    stage('build') {
      steps {
        sh "docker build -t ${env.ACR_ENDPOINT}/jenkins-user-java:latest $WORKSPACE/apis/user-java"
      }
    } 
    stage('push') {
      sh "docker push -t ${env.ACR_ENDPOINT}/jenkins-user-java:latest"
    }
  }
}
