pipeline {
    agent any



    environment {
        APP_NAME = 'devopsoh/api-trip'
        ACR_HOST = 'openhacktce4acr.azurecr.io'
        SRC_DIR = 'apis/trips'
        IMG_TAG = "${env.BUILD_TAG}"
    }

    stages{
        stage('Code Test') {
            steps {
                dir("${env.SRC_DIR}") {
                    sh '''
                        echo "Testing will occur here"
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${env.SRC_DIR}") {
                    script {
                        docker.build("${env.ACR_HOST}/${env.APP_NAME}:${env.IMG_TAG}")
                    }
                }
            }
        }


    }
}