name: Docker Build User Java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:

  publish:
    name: Docker Build User Java

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: chixcancode-projects/openhack-devops-team/user-java
        username: ${{ github.actor }}
        password: ${{ secrets.githubtoken }}
        registry: docker.pkg.github.com
        workdir: apis/user-java
        context: apis/user-java


