name: Build & Publish Trips Service to GH Packages

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:  
      - develop
jobs:
  build-and-push-trips:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.1.1
      with:
        github-token: ${{ secrets.githubtoken }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: user-java # Provide Docker image name
        build-context: ./apis/user-java # Provide path to the folder with the Dockerfile
