name: Linux Container Workflow

on:
  push:
    paths:
    - 'apis/poi/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: openhackcoachrw33acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build apis/poi/web -t openhackcoachrw33acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
        docker push openhackcoachrw33acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'myapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'openhackcoachrw33acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}'
