name: PR

on:
  push:
    branches:
      - master

env:
  ACRNAME: openhackcgb03xk8acr
  RESOURCE_GROUP: openhackcgb03xk8rg

jobs:
  build-poi:
    name: POI Build and Push Image
    runs-on: ubuntu-latest
    env:
      REGISTRY_PASSWORD: ${{ secrets.REG_PASSWORD }}
      REGISTRY_USERNAME: ${{ secrets.REG_USERNAME }}
    steps:
      - uses: actions/checkout@v1
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker build
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            BASEIMAGETAG=${{github.sha}}

            echo "Building API-POI image..."
            echo "Changing directory to $GITHUB_WORKSPACE/apis/poi/web..."
            cd "$GITHUB_WORKSPACE/apis/poi/web"
            az acr build --image "devopsoh/api-poi:${BASEIMAGETAG}" --registry $ACRNAME --file Dockerfile .

  build-trips:
    name: Trips Build and Push Image
    runs-on: ubuntu-latest
    env:
      REGISTRY_PASSWORD: ${{ secrets.REG_PASSWORD }}
      REGISTRY_USERNAME: ${{ secrets.REG_USERNAME }}
    steps:
      - uses: actions/checkout@v1
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker build
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            BASEIMAGETAG=${{github.sha}}

            echo "Building API-TRIPS image..."
            echo "Changing directory to $GITHUB_WORKSPACE/apis/trips..."
            cd "$GITHUB_WORKSPACE/apis/trips"
            az acr build --image "devopsoh/api-trips:${BASEIMAGETAG}" --registry $ACRNAME --file Dockerfile .

  build-userprofile:
    name: Userprofile Build and Push Image
    runs-on: ubuntu-latest
    env:
      REGISTRY_PASSWORD: ${{ secrets.REG_PASSWORD }}
      REGISTRY_USERNAME: ${{ secrets.REG_USERNAME }}
    steps:
      - uses: actions/checkout@v1
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker build
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            BASEIMAGETAG=${{github.sha}}

            echo "Building API-USERPROFILE image..."
            echo "Changing directory to $GITHUB_WORKSPACE/apis/userprofile..."
            cd "$GITHUB_WORKSPACE/apis/userprofile"
            az acr build --image "devopsoh/api-userprofile:${BASEIMAGETAG}" --registry $ACRNAME --file Dockerfile .

  build-user-java:
    name: User Java Build and Push Image
    runs-on: ubuntu-latest
    env:
      REGISTRY_PASSWORD: ${{ secrets.REG_PASSWORD }}
      REGISTRY_USERNAME: ${{ secrets.REG_USERNAME }}
    steps:
      - uses: actions/checkout@v1
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker build
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            BASEIMAGETAG=${{github.sha}}

            echo "Building API-USER-JAVA image..."
            echo "Changing directory to $GITHUB_WORKSPACE/apis/user-java..."
            cd "$GITHUB_WORKSPACE/apis/user-java"
            az acr build --image "devopsoh/api-user-java:${BASEIMAGETAG}" --registry $ACRNAME --file Dockerfile .

  publish-poi:
    name: Publish POI
    environment: poi
    needs:
      - build-poi
    runs-on: ubuntu-latest
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: openhackcgb03xk8poi
          images: devopsoh/api-poi:${{github.sha}}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}

  publish-trips:
    name: Publish trips
    environment: trips
    needs:
      - build-trips
    runs-on: ubuntu-latest
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: openhackcgb03xk8trips
          images: devopsoh/api-trips:${{github.sha}}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}

  publish-userprofile:
    name: Publish userprofile
    environment: userprofile
    needs:
      - build-userprofile
    runs-on: ubuntu-latest
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: openhackcgb03xk8userprofile
          images: devopsoh/api-userprofile:${{github.sha}}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}

  publish-user-java:
    name: Publish user java
    environment: userjava
    needs:
      - build-user-java
    runs-on: ubuntu-latest
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: openhackcgb03xk8userjava
          images: devopsoh/api-user-java:${{github.sha}}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}