name: PR

on:
  push:
    branches:
      - master

env:
  ACRNAME: openhackcgb03xk8acr
  RESOURCE_GROUP: openhackcgb03xk8rg

jobs:
  build-poi:
    name: POI Build and Push Image
    runs-on: ubuntu-latest
    env:
      REGISTRY_PASSWORD: ${{ secrets.REG_PASSWORD }}
      REGISTRY_USERNAME: ${{ secrets.REG_USERNAME }}
    steps:
      - uses: actions/checkout@v1
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker build
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            BASEIMAGETAG=${{github.sha}}

            echo "Building API-POI image..."
            echo "Changing directory to $GITHUB_WORKSPACE/apis/poi/web..."
            cd "$GITHUB_WORKSPACE/apis/poi/web"
            az acr build --image "devopsoh/api-poi:${BASEIMAGETAG}" --registry $ACRNAME --file Dockerfile .

  build-trips:
    name: Trips Build and Push Image
    runs-on: ubuntu-latest
    env:
      REGISTRY_PASSWORD: ${{ secrets.REG_PASSWORD }}
      REGISTRY_USERNAME: ${{ secrets.REG_USERNAME }}
    steps:
      - uses: actions/checkout@v1
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker build
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            BASEIMAGETAG=${{github.sha}}

            echo "Building API-TRIPS image..."
            echo "Changing directory to $GITHUB_WORKSPACE/apis/trips..."
            cd "$GITHUB_WORKSPACE/apis/trips"
            az acr build --image "devopsoh/api-trips:${BASEIMAGETAG}" --registry $ACRNAME --file Dockerfile .

  build-userprofile:
    name: Userprofile Build and Push Image
    runs-on: ubuntu-latest
    env:
      REGISTRY_PASSWORD: ${{ secrets.REG_PASSWORD }}
      REGISTRY_USERNAME: ${{ secrets.REG_USERNAME }}
    steps:
      - uses: actions/checkout@v1
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker build
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            BASEIMAGETAG=${{github.sha}}

            echo "Building API-USERPROFILE image..."
            echo "Changing directory to $GITHUB_WORKSPACE/apis/userprofile..."
            cd "$GITHUB_WORKSPACE/apis/userprofile"
            az acr build --image "devopsoh/api-userprofile:${BASEIMAGETAG}" --registry $ACRNAME --file Dockerfile .

  publish-poi:
    name: Publish POI
    environment: poi
    needs:
      - build-poi
    runs-on: ubuntu-latest
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: openhackcgb03xk8poi
          images: openhackcgb03xk8acr.azurecr.io/devopsoh/api-poi:${{github.sha}}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}

  publish-trips:
    name: Publish trips
    environment: trips
    needs:
      - build-trips
    runs-on: ubuntu-latest
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: openhackcgb03xk8trips
          images: openhackcgb03xk8acr.azurecr.io/devopsoh/api-trips:${{github.sha}}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}

  publish-userprofile-staging:
    name: Publish userprofile
    environment: userprofile
    needs:
      - build-userprofile
    runs-on: ubuntu-latest
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: openhackcgb03xk8userprofile
          images: openhackcgb03xk8acr.azurecr.io/devopsoh/api-userprofile:${{github.sha}}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}

  healthcheck-userprofile-staging:
    name: HealthCheck user profile
    needs:
      - publish-user-profile-staging
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          # Check the following URLs one by one sequentially
          url: https://openhackcgb03xk8userprofile.azurewebsites.net/api/healthcheck/user
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: no # Optional, defaults to "no"
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          # Retry all errors, including 404
          retry-all: no # Optional, defaults to "no"
  