name: .NET Core

on:
  pull_request:
    paths: 
      - '/apis/poi/**'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run a multi-line script
      shell: bash
      run: echo "test"  

