name: .NET Joel

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'
    paths: 
    - '/apis/poi/**.cs'
    - '/apis/poi/**.csproj'
  # additional events omitted for brevity
  push:
    branches: [ master ]
    paths:
    - '/apis/poi/**.cs'
    - '/apis/poi/**.csproj'
 

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
