name: Error

on: [push]

jobs:
  error:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Throw error in PowerShell script
        run: |
          throw 'something failed';
      - name: The job has failed
        uses: hacker5f9s/azuredevops-bug-action@v1
        if: failure()
        with:
          OrganizationName: "hacker5f9s"
          PAT: "PAT"
          ProjectName: "TripViewer" #Contoso
          AreaPath: "TripViewer\\Automation" #Contoso\\Automation
          IterationPath: "TripViewer" #Contoso
          GithubToken: "GithubToken" #GithubToken
          WorkflowFileName: "error.yml" 
        env:
          PAT: ${{ secrets.PAT}}
          GithubToken: ${{ secrets.githubtoken}}
