# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - openhackl8y6u383trips

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/ohnovt7/openhack-devops-team/
        username: ${{ secrets.AzureAppService_ContainerUsername_cc33740538c24c6daeb7eacf35aa9865 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4abd1076e70840fcb496a5352ea044bd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/ohnovt7/openhack-devops-team/${{ secrets.AzureAppService_ContainerUsername_cc33740538c24c6daeb7eacf35aa9865 }}/api-trips:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackl8y6u383trips'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a1cc61f701204cd7b04b8ef808e798fb }}
        images: 'ghcr.io/ohnovt7/openhack-devops-team/${{ secrets.AzureAppService_ContainerUsername_cc33740538c24c6daeb7eacf35aa9865 }}/api-trips:${{ github.sha }}'