# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    paths: 
      - 'apis/userprofile/**'

defaults:
  run:
    working-directory: apis/userprofile/

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Create issue if job failed
      uses: JasonEtco/create-an-issue@v2.4.0
      if: ${{ failure() }} #https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#failure
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:      
        assignees: anujb
