# This is a basic workflow to help you get started with Actions
name: PR POI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'apis/userprofile/**'
  pull_request:
    branches: [ master ]

#on: push

jobs:          
  quality-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Quality
        run: |
          cd apis/userprofile
          npm i
          npm run test   
