# This is a basic workflow to help you get started with Actions
name: PR Trips

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
     paths:
      - 'apis/trips/**'
  pull_request:
    branches: [ master ]


jobs:
  quality-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Quality
        run: |
          cd apis/trips
          go test ./tests 
