# This is a basic workflow to help you get started with Actions
name: PR Trips

# Controls when the action will run.
on:
# Triggers the workflow on push or pull request events but only for the master branch
pull_request:
branches: [ master ]
paths:
- 'apis/trips/**'

jobs:
quality-cs:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Install dependencies
run: dotnet restore
- name: Build
run: dotnet build
- name: Test with the dotnet CLI
run: dotnet test

quality-go:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Quality
run: |
go test ./tests
