 # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions aa
name: Userprofile CI
on:
  push:
    paths: 
    - 'apis/userprofile/**'
    - '.github/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'apis/userprofile/**'
    - '.github/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install --prefix apis/userprofile/
    - name: Run Tests
      run: npm test --prefix apis/userprofile/
  
  error:
     - name: My first step
     uses: monacorp/action-name@master
     - name: My backup step
     if: ${{ failure() }}
     uses: actions/heroku@master
