name: Test trips service

# on:
#   push:
#     paths:
#     - 'apis/trips'
#   pull_request:
#     paths:
#     - 'apis/trips'

on: [push, pull_request]

env:
  working-directory: ./apis/trips/


jobs:

  lint:
    name: Lint
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: |
          go get -u golang.org/x/lint/golint 
          make lint
        working-directory: ${{env.working-directory}}

  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
        working-directory: ${{env.working-directory}}

      - name: Run build
        run: go build .
        working-directory: ${{env.working-directory}}

      - name: Run vet & lint
        run: |
          go vet .
          golint .
        working-directory: ${{env.working-directory}}

      - name: Run Tests
        run: cd ./tests && go test -v .
        working-directory: ${{env.working-directory}}
