name: Test trips service

# on:
#   push:
#     paths:
#     - 'apis/trips'
#   pull_request:
#     paths:
#     - 'apis/trips'

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Run build
      run: go build .

    - name: Run vet & lint
      run: |
        go vet .
        golint .

    - name: Run Tests
      run: cd ./apis/trips/tests/ && go test -v .
