name: Build trips service

on:
  push:
    branches:
    - master
    paths:
    - 'apis/trips/**'
  pull_request:
    branches:
    - master
    paths:
    - 'apis/trips/**'

env:
  working-directory: ./apis/trips/
  acrname: openhackdz41qgg3acr.azurecr.io


jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: [test]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
        working-directory: ${{env.working-directory}}

      - name: Run build
        run: az acr build --image "devopsoh/api-trips:${{ github.run_id }}" --registry ${{ env.acrname }} --file Dockerfile .
        working-directory: ${{env.working-directory}}

      - name: The job has failed
        if: ${{ failure() }}
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "title": "Trips Service Build has failed: ${{ github.run_id }}",
              "body": "Trips Service Build has failed: **${{ github.workflow }}**. \n\n Failure in run: _${{ github.run_id }}_."
              }'
