# This workflow will build a Java project with Maven
name: User-Java-CI
on:
  push:
    paths: 
    - 'apis/user-java/**'
    - '.github/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'apis/user-java/**'
    - '.github/**' 
jobs:
  build:
    name: user-java build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install -f ./apis/user-java/
    - name: Run Test
      run: mvn test -f ./apis/user-java
