name: CI for user-java API

on:
  push:
    branches: 
    - master
    paths:
    - 'apis/user-java/**'

env:
  working-directory: ./apis/user-java
  acrname: openhackdz41qgg3acr.azurecr.io
  appname: openhackdz41qgg3userjava

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds:  ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account show

      - name: Run build
        run: az acr build --image "devopsoh/api-user-java:${{ github.run_id }}" --registry ${{ env.acrname }} --file Dockerfile .
        working-directory: ${{env.working-directory}}

      - name: WebApp deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.appname }}
          slot-name: staging
          images: ${{ env.acrname }}/devopsoh/api-user-java:${{ github.run_id }}

      - name: The job has failed
        if: ${{ failure() }}
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "title": "User-Java Service Build has failed: ${{ github.run_id }}",
              "body": "User-Java Service Build has failed: **${{ github.workflow }}**. \n\n Failure in run: _${{ github.run_id }}_."
              }'
