trigger:
  branches:
    include:
    - master
  paths:
    include:
    - apis/userprofile/*
    exclude:
    - apis/trips/*
    - apis/user-java/*
    - apis/poi/*
resources:
  repositories:
  - repository: self
variables:
- name: tag
  value: '$(Build.BuildId)'
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: OpenHackACR
    - task: Docker@2
      displayName: Build and Push image
      inputs:
        command: buildAndPush
        containerRegistry: OpenHackACR
        repository: devopsoh/api-userprofile
        dockerfile: '$(Build.SourcesDirectory)/apis/userprofile/Dockerfile'
        tags: |
          $(tag)
  - job: ErrorHandler
    dependsOn:
    - Build
    condition: failed()
    steps:
    - task: CreateWorkItem@1
      inputs:
        workItemType: bug
        title: 'Build failed ($Build.BuildId)'
        authToken: $(System.AccessToken)
      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
      displayName: 'Create work item on failure'

