name: Build – userprofile service

on:
  push:
    branches:
    - master
    paths:
    - 'apis/userprofile/**'

env:
  working-directory: ./apis/userprofile/
  acrname: openhackdz41qgg3acr.azurecr.io
  app_name: api-userprofile


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account show
            
      - name: Run build
        run: az acr build --image "devopsoh/${{ env.app_name }}:${{ github.run_id }}" --registry ${{ env.acrname }} --file Dockerfile .
        working-directory: ${{env.working-directory}}

      - name: The job has failed
        if: ${{ failure() }}
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "title": "${{ env.app_name }} Service Build has failed: ${{ github.run_id }}",
              "body": "${{ env.app_name }} Service Build has failed: **${{ github.workflow }}**. \n\n Failure in run: _${{ github.run_id }}_."
              }'
