# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'devopsopenhack/poi-web:$(build.buildId)'
  dockerfilePath: 'apis/poi/web/Dockerfile'
  dockerContext: 'apis/poi/web'

steps:
- script: docker build -f $(dockerfilePath) -t $(imageName) $(dockerContext)
  displayName: 'docker build poi-web'
- script: docker tag $(imageName) $(containerRegistry)/$(imageName)
  displayName: Tag the image
- script: |
    docker login -u $(dockerId) -p $(dockerpswd)
    docker push $(dockerId)/$(imageName)
  displayName: Auth to registry and push
